### ISSUE TITLE
Error compiling: multiple definition of `style`

### ISSUE THREAD

**Issue by pzl** [Ja-sonYun/sequence-diagram-cli#9]
I think you've got a header include loop or something. (main.h includes renderer.h which includes style.h -- and style.c -> style.h)

```
gcc main.o arrow_connection.o participant.o renderer.o parser.o scanner.o style.o fetch.o -o seqdia -I/usr/local/opt/curl/include -L/usr/local/opt/curl/lib -lcurl
/usr/bin/ld: renderer.o:(.bss+0x0): multiple definition of `style'; main.o:(.bss+0x0): first defined here
/usr/bin/ld: style.o:(.bss+0x0): multiple definition of `style'; main.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:22: seqdia] Error 1
```

**Comment by Ja-sonYun** [comment]
@pzl that is weird. I was able to compile on linux x86 and arm without any error(except warning).
Please let me know your platform. I'm still learning c and others related to c, your feedback would be very helpful for my study.
